###

POST http://localhost:8080/api/user/select
Content-Type: application/json

userid

###

POST http://localhost:8080/api/user/create
Content-Type: application/json

{
    "userid": "userid",
    "password": "password",
    "name": "부종민"
}

###


